# ==========================================
# Database Configuration
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/shoply
spring.datasource.username=root
spring.datasource.password=Mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA / Hibernate Configuration
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ==========================================
# Server Configuration
# ==========================================
server.port=8080

# ==========================================
# JWT Configuration
# ==========================================
jwt.secret=YourSecretKeyForShoplyApplication123456789
jwt.expiration=86400000

# ==========================================
# Razorpay Test Configuration
# ==========================================
razorpay.key.id=rzp_test_TE9OzmTZDzBCAD
razorpay.key.secret=eRuVxTIFf3tohQT7zFKivKgv

# ==========================================
# Email Configuration
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=samarthadhao2019@gmail.com
spring.mail.password=qntp tuvf rqdd bkwx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ==========================================
# Logging
# ==========================================
logging.level.org.springframework.mail=INFO
logging.level.org.springframework.security=INFO